spring:
  datasource:
      url: jdbc:mysql://192.168.1.222:3306/dianbo?useUnicode=true&autoReconnect=true&useSSL=false
      username: root
      password: 111111
  cloud:
    config:
      allow-override: true
      override-none: true #不覆盖非系统属性
      override-system-properties: false #覆盖系统属性
  redis:
      host: 192.168.1.222
      port: 6379

server:
  port: 8008

vlight:
  kafka:
    topic:
      userDelete: user-delete

dianbo:
  feign:
    content:
      url: http://192.168.1.222:9002
    user:
      url: http://192.168.1.222:9001

endpoints:
  shutdown:
    enabled: true

management:
  security:
    enabled: false

api:
  platform:
    neteaseIMAppKey: de2cda341e38c5dee39435fd636d9776
    neteaseIMSecret: 009b0c5b6e51
    neteaseIMApiUrl: https://api.netease.im/nimserver
refresh: hello
